import Head from "next/head";
import styles from "../styles/Home.module.css";
import "../components/Header";
import ManualHeader from "../components/Header";
import HeaderCheet from "../components/HeaderCheet";
import LotteryEntrance from "../components/LotteryEntrance";

export default function Home() {
  return (
    <div className="bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center flex-grow min-h-screen px-0 py-16">
        <div className="p-9">
          <h1 className="text-6xl m-0 font-black font-verdana text-white ">
            Welcome to the Lottery!
          </h1>
        </div>

        {/*<ManualHeader></ManualHeader>*/}
        <HeaderCheet></HeaderCheet>
        <LotteryEntrance></LotteryEntrance>
      </main>
    </div>
  );
}
